# Configuration for ticker
background_color: [255, 165, 0]  # Background color in RGB
font_color: [255, 255, 255]      # Font color in RGB
direction: left                  # Direction of ticker: left(<--) or right(-->)
ticker_text: "Breaking News: This is a configurable ticker!"  # Text to display
position: bottom                 # Position of ticker: top or bottom
logo_path: ""                    # Path to logo image (leave empty if no logo)
logo_position: left             # Position of logo: left or right